/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AiTutorRouteImport } from './routes/ai-tutor'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegisterSplatRouteImport } from './routes/register.$'
import { Route as LoginSplatRouteImport } from './routes/login.$'
import { Route as CourseCourseSlugRouteImport } from './routes/course.$courseSlug'
import { Route as ApiTutorRouteImport } from './routes/api/tutor'
import { Route as CourseCourseSlugTopicSlugRouteImport } from './routes/course.$courseSlug.$topicSlug'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AiTutorRoute = AiTutorRouteImport.update({
  id: '/ai-tutor',
  path: '/ai-tutor',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterSplatRoute = RegisterSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => RegisterRoute,
} as any)
const LoginSplatRoute = LoginSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => LoginRoute,
} as any)
const CourseCourseSlugRoute = CourseCourseSlugRouteImport.update({
  id: '/course/$courseSlug',
  path: '/course/$courseSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTutorRoute = ApiTutorRouteImport.update({
  id: '/api/tutor',
  path: '/api/tutor',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseCourseSlugTopicSlugRoute =
  CourseCourseSlugTopicSlugRouteImport.update({
    id: '/$topicSlug',
    path: '/$topicSlug',
    getParentRoute: () => CourseCourseSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/ai-tutor': typeof AiTutorRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRouteWithChildren
  '/register': typeof RegisterRouteWithChildren
  '/api/tutor': typeof ApiTutorRoute
  '/course/$courseSlug': typeof CourseCourseSlugRouteWithChildren
  '/login/$': typeof LoginSplatRoute
  '/register/$': typeof RegisterSplatRoute
  '/course/$courseSlug/$topicSlug': typeof CourseCourseSlugTopicSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/ai-tutor': typeof AiTutorRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRouteWithChildren
  '/register': typeof RegisterRouteWithChildren
  '/api/tutor': typeof ApiTutorRoute
  '/course/$courseSlug': typeof CourseCourseSlugRouteWithChildren
  '/login/$': typeof LoginSplatRoute
  '/register/$': typeof RegisterSplatRoute
  '/course/$courseSlug/$topicSlug': typeof CourseCourseSlugTopicSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/ai-tutor': typeof AiTutorRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRouteWithChildren
  '/register': typeof RegisterRouteWithChildren
  '/api/tutor': typeof ApiTutorRoute
  '/course/$courseSlug': typeof CourseCourseSlugRouteWithChildren
  '/login/$': typeof LoginSplatRoute
  '/register/$': typeof RegisterSplatRoute
  '/course/$courseSlug/$topicSlug': typeof CourseCourseSlugTopicSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/ai-tutor'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/api/tutor'
    | '/course/$courseSlug'
    | '/login/$'
    | '/register/$'
    | '/course/$courseSlug/$topicSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/ai-tutor'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/api/tutor'
    | '/course/$courseSlug'
    | '/login/$'
    | '/register/$'
    | '/course/$courseSlug/$topicSlug'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/ai-tutor'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/api/tutor'
    | '/course/$courseSlug'
    | '/login/$'
    | '/register/$'
    | '/course/$courseSlug/$topicSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AiTutorRoute: typeof AiTutorRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRouteWithChildren
  RegisterRoute: typeof RegisterRouteWithChildren
  ApiTutorRoute: typeof ApiTutorRoute
  CourseCourseSlugRoute: typeof CourseCourseSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-tutor': {
      id: '/ai-tutor'
      path: '/ai-tutor'
      fullPath: '/ai-tutor'
      preLoaderRoute: typeof AiTutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/$': {
      id: '/register/$'
      path: '/$'
      fullPath: '/register/$'
      preLoaderRoute: typeof RegisterSplatRouteImport
      parentRoute: typeof RegisterRoute
    }
    '/login/$': {
      id: '/login/$'
      path: '/$'
      fullPath: '/login/$'
      preLoaderRoute: typeof LoginSplatRouteImport
      parentRoute: typeof LoginRoute
    }
    '/course/$courseSlug': {
      id: '/course/$courseSlug'
      path: '/course/$courseSlug'
      fullPath: '/course/$courseSlug'
      preLoaderRoute: typeof CourseCourseSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tutor': {
      id: '/api/tutor'
      path: '/api/tutor'
      fullPath: '/api/tutor'
      preLoaderRoute: typeof ApiTutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/$courseSlug/$topicSlug': {
      id: '/course/$courseSlug/$topicSlug'
      path: '/$topicSlug'
      fullPath: '/course/$courseSlug/$topicSlug'
      preLoaderRoute: typeof CourseCourseSlugTopicSlugRouteImport
      parentRoute: typeof CourseCourseSlugRoute
    }
  }
}

interface LoginRouteChildren {
  LoginSplatRoute: typeof LoginSplatRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginSplatRoute: LoginSplatRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

interface RegisterRouteChildren {
  RegisterSplatRoute: typeof RegisterSplatRoute
}

const RegisterRouteChildren: RegisterRouteChildren = {
  RegisterSplatRoute: RegisterSplatRoute,
}

const RegisterRouteWithChildren = RegisterRoute._addFileChildren(
  RegisterRouteChildren,
)

interface CourseCourseSlugRouteChildren {
  CourseCourseSlugTopicSlugRoute: typeof CourseCourseSlugTopicSlugRoute
}

const CourseCourseSlugRouteChildren: CourseCourseSlugRouteChildren = {
  CourseCourseSlugTopicSlugRoute: CourseCourseSlugTopicSlugRoute,
}

const CourseCourseSlugRouteWithChildren =
  CourseCourseSlugRoute._addFileChildren(CourseCourseSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AiTutorRoute: AiTutorRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRouteWithChildren,
  RegisterRoute: RegisterRouteWithChildren,
  ApiTutorRoute: ApiTutorRoute,
  CourseCourseSlugRoute: CourseCourseSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
